version: '2'
services:
  app:
    image: registry.spin.nersc.gov/perssongroup/mp-minio-app:latest
    user: 60141:60141
    ports:
      - 60013:9000
    cap_drop:
      - ALL
    command:
      ["server", "data"]
    env_file:
      - minio-keys.env
    volumes:
      - /global/project/projectdirs/matgen/spin-stacks/mp-minio/data:/data
  web:
    image: registry.spin.nersc.gov/perssongroup/mp-minio-web:latest
    ports:
      - 60014:8080
    user: 60141:60141
    volumes:
      - /global/project/projectdirs/matgen/spin-stacks/mp-minio/web/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    group_add:
    - nginx
    cap_drop:
    - ALL

