version: '2'
services:
  app:
    image: registry.spin.nersc.gov/perssongroup/mp-minio-app:latest
    user: 60141:60141
    cap_drop:
      - ALL
    command:
      ["server", "data"]
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniosecret
  web:
    image: registry.spin.nersc.gov/perssongroup/mp-minio-web:latest
    user: 60141:60141
    ports:
      - "60012:9000"
    expose:
      - "60012"
    volumes:
      - /global/project/projectdirs/matgen/spin-stacks/mp-minio-dev/data:/data
    cap_drop:
      - ALL

